# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qFUIAGWShFLzN5AqznJ8HRknFMCEA9dk

# The RAG Pipeline (Chunking -> Vector Store -> Generation)

Objective:  
You will learn why "how you read" data (Chunking) matters as much as "what you read," and you will build a Retrieval Augmented Generation (RAG) pipeline.

# Section 0: Setup & Prerequisites

Install the necessary libraries. You will likely need langchain, langchain-community, chromadb, and an embedding provider.
"""

# INITIAL SETUP (RUN THIS ONCE)

# 1. Install dependencies with specific versions to avoid conflicts
!pip install -q -U \
  torch \
  transformers \
  sentence-transformers \
  accelerate \
  bitsandbytes \
  langchain \
  langchain-community \
  chromadb \
  pysqlite3-binary

# 2. Fix Colab's SQLite version issue (Must happen before importing chromadb)
__import__('pysqlite3')
import sys
sys.modules['sqlite3'] = sys.modules.pop('pysqlite3')

# 3. Check if GPU is available
import torch
if not torch.cuda.is_available():
    print("WARNING: You are running on CPU. Go to Runtime -> Change runtime type -> T4 GPU")
else:
    print(f" GPU Detected: {torch.cuda.get_device_name(0)}")

# TODO: Import any other necessary libraries here
# !pip install ...

"""# Section 1: Chunking Experiment

LLMs have context windows. We must slice our data. But if you slice a sentence in half, the meaning might be lost. Let's prove this.
"""

# Create a small sample text file for chunking experiments

sample_text = """
Arjun was born in Chennai and grew up with a strong interest in science.
He studied electrical engineering during his undergraduate years.

After graduation, Arjun moved to Bangalore where he began working at a startup.
His role involved building machine learning systems for real-world problems.

Later, he decided to pursue research and focused on large language models.
His work explored how transformers understand context and meaning in long documents.
"""

# Create a data folder
import os
os.makedirs("data", exist_ok=True)

# Write the file
with open("data/my_chapter.txt", "w", encoding="utf-8") as f:
    f.write(sample_text)

#print("File created at data/my_chapter.txt")

# Load a text file of your choice

filename = "data/my_chapter.txt"

def load_data(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


raw_text = load_data(filename)
print(f"Loaded {len(raw_text)} characters.")

"""Implement a splitter that strictly cuts text every x characters, regardless of sentence boundaries."""

def naive_splitter(text, chunk_size=100):
    """
    Splits text strictly by character count.
    Returns: List[str]
    """
    chunks=[]
    for i in range(0, len(text),chunk_size):
        chunks.append(text[i:i+chunk_size])
    return chunks

naive_chunks = naive_splitter(raw_text)

"""Use a library (like LangChain) to split by "separators" (Paragraphs $\rightarrow$ Sentences $\rightarrow$ Words) to preserve meaning."""

# Initialize a RecursiveCharacterTextSplitter

import langchain

from langchain_text_splitters import RecursiveCharacterTextSplitter
specific_splitter = RecursiveCharacterTextSplitter(
    chunk_size=100,           # (x)A chunk can be 500 charecters OR less
    chunk_overlap=20            # (t)
)

semantic_chunks = specific_splitter.split_text(raw_text)

#print(f"Created {len(semantic_chunks)} semantic chunks")
#print(semantic_chunks[0][:300])

"""Find a specific example where the Naive splitter broke a sentence in half, rendering it meaningless, but the Semantic splitter kept it intact"""

def find_broken_context(naive_chunks, semantic_chunks):

    print("NAIVE CHUNK \n")
    print(naive_chunks[1])

    print("\nSEMANTIC CHUNK\n")
    print(semantic_chunks[1])

find_broken_context(naive_chunks, semantic_chunks)

"""In a text cell below, explain why the overlap parameter in the recursive splitter is essential for retrieval tasks.

Chunk overlap prevents important context from being split across chunks.
By repeating boundary text, each chunk remains meaningful on its own.
This improves retrieval accuracy in RAG systems.

# Section 2: Vector Storage

We will convert our semantic_chunks into vector embeddings and store them.

Initialize Embeddings & DB:
- You may use OpenAI Embeddings (if you have a key) or HuggingFace (all-MiniLM-L6-v2) for a free, local alternative.
- Use ChromaDB or FAISS as your store.
"""

# TODO: Initialize your Embedding Model
from langchain_community.embeddings import HuggingFaceEmbeddings

embedding_function = HuggingFaceEmbeddings(
    model_name="all-MiniLM-L6-v2"
)

from langchain_community.vectorstores import Chroma

vector_db = Chroma.from_texts(
    texts=semantic_chunks,
    embedding=embedding_function,
    persist_directory="./chroma_db"
)

print("Vector Store successfully created.")

"""# Section 3: The MVP (Retrieval Loop)

We have the brain (LLM) and the memory (Vector DB). Now we need to wire them together.

Create a function that takes a user query, converts it to a vector, and finds the top 3 most relevant chunks from your database.
"""

def retrieve_context(query, k=3):
    """
    Args:
        query (str): The user's question
        k (int): Number of chunks to retrieve
    Returns:
        List[str]: The top k context chunks
    """

    results = vector_db.similarity_search(query, k=k)
    return [doc.page_content for doc in results]

# Test it
test_query = "Where was Arjun born?"
context_results = retrieve_context(test_query)
print(f"Retrieved {len(context_results)} chunks.")

"""Construct the final prompt. You must inject the retrieved context into the system prompt so the LLM answers only based on that data."""

# TODO: Initialize your LLM (OpenAI, Anthropic, or a local Llama via Ollama/HuggingFace)
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(model_name)
llm = AutoModelForSeq2SeqLM.from_pretrained(model_name)

def generate_answer(query):
    # 1. Retrieve context
    context_chunks = retrieve_context(query)
    context_str = "\n".join(context_chunks)

    # 2. Construct the Prompt
    # Constraint: The prompt must instruct the LLM to say "I don't know" if the info isn't in the chunks.
    prompt = f"""
Answer the question using ONLY the context below.
If the answer is not present, say "I don't know".

Context:
{context_str}

Question:
{query}

Answer:
"""

    # 3. Pass to LLM and return response
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True)
    outputs = llm.generate(**inputs, max_new_tokens=150)
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return response
# Final Test
answer = generate_answer("Where was Arjun born?")
print(answer)

"""# The End (of task 3)"""