# -*- coding: utf-8 -*-
"""week1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rOw4JCOwFMjlNEe7FuKPm05YPMh7p70n
"""

import csv
from sentence_transformers import SentenceTransformer

words = [
    # Fruits
    "Apples", "Banana", "Orange", "Grape", "Strawberry",
    # Tech companies
    "Alphabet", "Microsoft", "Apple Inc.", "Meta", "Amazon",
    # Sports
    "Football", "Tennis", "Basketball", "Golf", "Squash",
    # Planets
    "Mercury", "Saturn", "Earth", "Jupiter", "Venus"
]

# using the all-MiniLM-L6-v2 model
model = SentenceTransformer('all-MiniLM-L6-v2')

# encoding the words
embeddings = model.encode(words)

# metadata.tsv
with open('metadata.tsv', 'w') as f:
    for word in words:
        f.write(f"{word}\n")

# vectors.tsv
with open('vectors.tsv', 'w') as f:
    tsv_writer = csv.writer(f, delimiter='\t')
    for vector in embeddings:
        tsv_writer.writerow(vector)