[project]
name = "mini-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "streamlit>=1.44.1",
    "groq>=0.27.0",
    "langchain-chroma>=0.2.3",
    "langchain-huggingface>=0.1.2",
    "langchain-text-splitters>=0.3.8",
    "rank-bm25>=0.2.2",
    "pysqlite3>=0.6.0",
    "sentence-transformers>=3.4.1",
    "chromadb>=1.0.0",
    "torch>=2.7.0",
    "tqdm>=4.67.1",
    "transformers>=4.51.3",
    "torchvision>=0.26.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "pytest>=9.0.3",
    "ruff>=0.15.12",
]
